name: Example workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high --sarif-file-output=snyk.sarif
      - name: Print the snyk sarif file
        run : cat snyk.sarif
      - name : Total security issues
        run : |
          length=$(cat snyk.sarif | jq '.runs[0].results | length')
          echo "RESULTS_LENGTH=$length" >> $GITHUB_ENV
      - name: Pass_or_Fail_the_job
        run: |
          if [ "$RESULTS_LENGTH" != 0 ]; then
            echo "Job Failed"
            exit 1
          else
            echo "Pass"
          fi
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        if: always()
        with:
          payload: |
            {
              "text": "The Snyk scan result for repo , snykgithubdemoyt, is : ${{ job.status }} \n*"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
